trainer:
  accelerator: cuda
  max_epochs: 5
  check_val_every_n_epoch: 10
  log_every_n_steps: 5
model:
  arch: unet
  encoder_name: resnet18
  encoder_weights: null
  in_channels: 1
  classes: 4
data:
  image_size: [320, 224]
  disk_max_num: 10
  labeled_disks: 3
  train_items: 100
  valid_items: 10
  test_items: 10
  batch_size: 4
  num_workers: 3
logger:
  experiment_name: deep_circle_counter
  log_model: true
  tracking_uri: file:/tmp/logs